# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"7\n\x0ePredictRequest\x12\x11\n\tinput_ids\x18\x01 \x03(\x05\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\"5\n\x0fPredictResponse\x12\x12\n\noutput_ids\x18\x01 \x03(\x05\x12\x0e\n\x06logits\x18\x02 \x03(\x02\"\x0f\n\rHealthRequest\"-\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x93\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12=\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=85
  _globals['_PREDICTRESPONSE']._serialized_start=87
  _globals['_PREDICTRESPONSE']._serialized_end=140
  _globals['_HEALTHREQUEST']._serialized_start=142
  _globals['_HEALTHREQUEST']._serialized_end=157
  _globals['_HEALTHRESPONSE']._serialized_start=159
  _globals['_HEALTHRESPONSE']._serialized_end=204
  _globals['_INFERENCESERVICE']._serialized_start=207
  _globals['_INFERENCESERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
